RunWhen ACR Helm Updater (#4)

diff --git a/codebundles/azure-rw-acr-sync/.test/Taskfile.yaml b/codebundles/azure-rw-acr-sync/.test/Taskfile.yaml
--- a/codebundles/azure-rw-acr-sync/.test/Taskfile.yaml
+++ b/codebundles/azure-rw-acr-sync/.test/Taskfile.yaml
@@ -2,65 +2,27 @@ version: "3"
 
 tasks:
   default:
-    desc: "Run/refresh config"
+    desc: "Generate workspaceInfo and rebuild/test"
     cmds:
-      - task: check-unpushed-commits
       - task: generate-rwl-config
       - task: run-rwl-discovery
 
   clean:
     desc: "Run cleanup tasks"
     cmds:
-      - task: delete-slxs
+      - task: check-and-cleanup-terraform
       - task: clean-rwl-discovery
 
   build-infra:
     desc: "Build test infrastructure"
     cmds:
+      - task: build-terraform-infra
 
 
-  check-unpushed-commits:
-    desc: Check if outstanding commits or file updates need to be pushed before testing.
-    vars:
-      # Specify the base directory relative to your Taskfile location
-      BASE_DIR: "../"
-    cmds:
-      - |
-        echo "Checking for uncommitted changes in $BASE_DIR and $BASE_DIR.runwhen, excluding '.test'..."
-        UNCOMMITTED_FILES=$(git diff --name-only HEAD | grep -E "^${BASE_DIR}(\.runwhen|[^/]+)" | grep -v "/\.test/" || true)
-        if [ -n "$UNCOMMITTED_FILES" ]; then
-          echo "✗"
-          echo "Uncommitted changes found:"
-          echo "$UNCOMMITTED_FILES"
-          echo "Remember to commit & push changes before executing the `run-rwl-discovery` task."
-          echo "------------"
-          exit 1    
-        else
-          echo "√"
-          echo "No uncommitted changes in specified directories."
-          echo "------------"        
-        fi
-      - |
-        echo "Checking for unpushed commits in $BASE_DIR and $BASE_DIR.runwhen, excluding '.test'..."
-        git fetch origin
-        UNPUSHED_FILES=$(git diff --name-only origin/$(git rev-parse --abbrev-ref HEAD) HEAD | grep -E "^${BASE_DIR}(\.runwhen|[^/]+)" | grep -v "/\.test/" || true)
-        if [ -n "$UNPUSHED_FILES" ]; then
-          echo "✗"
-          echo "Unpushed commits found:"
-          echo "$UNPUSHED_FILES"
-          echo "Remember to push changes before executing the `run-rwl-discovery` task."
-          echo "------------"
-          exit 1        
-        else
-          echo "√"
-          echo "No unpushed commits in specified directories."
-          echo "------------"        
-        fi
-    silent: true
   generate-rwl-config:
     desc: "Generate RunWhen Local configuration (workspaceInfo.yaml)"
     env:
-      ARM_SUBSCRIPTION_ID: "{{.ARM_SUBSCRIPTION_ID}}"
+      ARM_SUBSCRIPTION_ID: "{{.TF_VAR_subscription_id_1}}"
       AZ_TENANT_ID: "{{.AZ_TENANT_ID}}"
       AZ_CLIENT_SECRET: "{{.AZ_CLIENT_SECRET}}"
       AZ_CLIENT_ID: "{{.AZ_CLIENT_ID}}"
@@ -71,11 +33,29 @@ tasks:
         branch_name=$(git rev-parse --abbrev-ref HEAD)
         codebundle=$(basename "$(dirname "$PWD")")
 
+        # Fetch individual cluster details from Terraform state
+        pushd terraform > /dev/null
+        cluster_name=$(terraform show -json terraform.tfstate | jq -r '
+          .values.outputs.cluster_name.value')
+        cluster_server=$(terraform show -json terraform.tfstate | jq -r '
+          .values.outputs.cluster_fqdn.value')
+        cluster_resource_group=$(terraform show -json terraform.tfstate | jq -r '
+          .values.outputs.cluster_rg.value')
+        cluster_sub=$(terraform show -json terraform.tfstate | jq -r '
+          .values.outputs.cluster_sub.value')
+        popd > /dev/null
+
+        # Check if any of the required cluster variables are empty
+        if [ -z "$cluster1_name" ] || [ -z "$cluster1_server" ] || [ -z "$cluster1_resource_group" ]; then
+          echo "Error: Missing cluster details. Ensure Terraform plan has been applied."
+          exit 1
+        fi
+
         # Generate workspaceInfo.yaml with fetched cluster details
         cat <<EOF > workspaceInfo.yaml
         workspaceName: "$RW_WORKSPACE"
         workspaceOwnerEmail: authors@runwhen.com
-        defaultLocation: bd97d852-7cfe-4f24-8697-af70a1d8244a
+        defaultLocation: location-01
         defaultLOD: detailed
         cloudConfig:
           azure:
@@ -85,19 +65,18 @@ tasks:
             clientSecret: "$AZ_CLIENT_SECRET"
             aksClusters: 
               clusters: 
-                - name: aks-cl-1
-                  server: https://aks-cl-1-nftfei3p.hcp.eastus.azmk8s.io
-                  resource_group: azure-aks-1
-              resourceGroupLevelOfDetails:
-                azure-aks-1: basic
-        codeCollections:
+                - name: $cluster_name
+                  server: https://$cluster_server:443
+                  resource_group: $cluster_resource_group
+                  subscriptionId: $cluster_sub
+            resourceGroupLevelOfDetails:
+              $cluster_resource_group: detailed
+        codeCollections: []
         - repoURL: "$repo_url"
           branch: "$branch_name"
           codeBundles: ["$codebundle"]
         custom: 
-          private_registry: azure_acr
-          azure_acr_registry: runwhensandboxacr.azurecr.io
-          azure_service_principal_secret_name: azure-sp
+          kubernetes_distribution_binary: kubectl
         EOF
     silent: true
 
@@ -124,7 +103,7 @@ tasks:
 
         kubeconfig=$(echo $RW_FROM_FILE | jq -r  .kubeconfig)
 
-        docker run --name $CONTAINER_NAME -p 8081:8081 -v "$(pwd)":/shared -d ghcr.io/runwhen-contrib/runwhen-local:latest || {
+        docker run --name $CONTAINER_NAME -p 8081:8081 -v "$(pwd)":/shared -v $kubeconfig:/shared/kubeconfig -d ghcr.io/runwhen-contrib/runwhen-local:latest || {
           echo "Failed to start container"; exit 1;
         }
 
@@ -136,141 +115,107 @@ tasks:
         echo "Review generated config files under output/workspaces/"
     silent: true
 
-  validate-generation-rules:
-    desc: "Validate YAML files in .runwhen/generation-rules"
+  check-terraform-infra:
+    desc: "Check if Terraform has any deployed infrastructure in the terraform subdirectory"
     cmds:
       - |
-        for cmd in curl yq ajv; do
-          if ! command -v $cmd &> /dev/null; then
-            echo "Error: $cmd is required but not installed."
-            exit 1
-          fi
-        done
+        # Source Envs for Auth
+        source terraform/tf.secret
 
-        temp_dir=$(mktemp -d)
-        curl -s -o "$temp_dir/generation-rule-schema.json" https://raw.githubusercontent.com/runwhen-contrib/runwhen-local/refs/heads/main/src/generation-rule-schema.json
-
-        for yaml_file in ../.runwhen/generation-rules/*.yaml; do
-          echo "Validating $yaml_file"
-          json_file="$temp_dir/$(basename "${yaml_file%.*}.json")"
-          yq -o=json "$yaml_file" > "$json_file"
-          ajv validate -s "$temp_dir/generation-rule-schema.json" -d "$json_file" --spec=draft2020 --strict=false \
-          && echo "$yaml_file is valid." || echo "$yaml_file is invalid."
-        done
-
-        rm -rf "$temp_dir"
-    silent: true
-
-  check-rwp-config:
-    desc: Check if env vars are set for RunWhen Platform
-    cmds:
-      - |
-        missing_vars=()
-
-        if [ -z "$RW_WORKSPACE" ]; then
-          missing_vars+=("RW_WORKSPACE")
-        fi
-
-        if [ -z "$RW_API_URL" ]; then
-          missing_vars+=("RW_API_URL")
-        fi
-
-        if [ -z "$RW_PAT" ]; then
-          missing_vars+=("RW_PAT")
-        fi
-
-        if [ ${#missing_vars[@]} -ne 0 ]; then
-          echo "The following required environment variables are missing: ${missing_vars[*]}"
+        # Navigate to the Terraform directory
+        if [ ! -d "terraform" ]; then
+          echo "Terraform directory not found."
           exit 1
         fi
-    silent: true
+        cd terraform
 
-  upload-slxs:
-    desc: "Upload SLX files to the appropriate URL"
-    env:
-      RW_WORKSPACE: "{{.RW_WORKSPACE}}"
-      RW_API_URL: "{{.RW_API}}"
-      RW_PAT: "{{.RW_PAT}}"
-    cmds:
-      - task: check-rwp-config
-      - |
-        BASE_DIR="output/workspaces/${RW_WORKSPACE}/slxs"
-        if [ ! -d "$BASE_DIR" ]; then
-          echo "Directory $BASE_DIR does not exist. Upload aborted."
-          exit 1
+        # Check if Terraform state file exists
+        if [ ! -f "terraform.tfstate" ]; then
+          echo "No Terraform state file found in the terraform directory. No infrastructure is deployed."
+          exit 0
         fi
 
-        for dir in "$BASE_DIR"/*; do
-          if [ -d "$dir" ]; then
-            SLX_NAME=$(basename "$dir")
-            PAYLOAD=$(jq -n --arg commitMsg "Creating new SLX $SLX_NAME" '{ commitMsg: $commitMsg, files: {} }')
-            for file in slx.yaml runbook.yaml sli.yaml; do
-              if [ -f "$dir/$file" ]; then
-                CONTENT=$(cat "$dir/$file")
-                PAYLOAD=$(echo "$PAYLOAD" | jq --arg fileContent "$CONTENT" --arg fileName "$file" '.files[$fileName] = $fileContent')
-              fi
-            done
+        # List resources in Terraform state
+        resources=$(terraform state list)
 
-            URL="https://${RW_API_URL}/api/v3/workspaces/${RW_WORKSPACE}/branches/main/slxs/${SLX_NAME}"
-            echo "Uploading SLX: $SLX_NAME to $URL"
-            response_code=$(curl -X POST "$URL" \
-              -H "Authorization: Bearer $RW_PAT" \
-              -H "Content-Type: application/json" \
-              -d "$PAYLOAD" \
-              -w "%{http_code}" -o /dev/null -s)
-            
-            if [[ "$response_code" == "200" || "$response_code" == "201" ]]; then
-              echo "Successfully uploaded SLX: $SLX_NAME to $URL"
-            elif [[ "$response_code" == "405" ]]; then
-              echo "Failed to upload SLX: $SLX_NAME to $URL. Method not allowed (405)."
-            else
-              echo "Failed to upload SLX: $SLX_NAME to $URL. Unexpected response code: $response_code"
-            fi
-          fi
-        done
+        # Check if any resources are listed in the state file
+        if [ -n "$resources" ]; then
+          echo "Deployed infrastructure detected."
+          echo "$resources"
+          exit 0
+        else
+          echo "No deployed infrastructure found in Terraform state."
+          exit 0
+        fi
     silent: true
-  delete-slxs:
-    desc: "Delete SLX objects from the appropriate URL"
-    env:
-      RW_WORKSPACE: '{{.RW_WORKSPACE | default "my-workspace"}}'
-      RW_API_URL: "{{.RW_API}}"
-      RW_PAT: "{{.RW_PAT}}"
+
+  build-terraform-infra:
+    desc: "Run terraform apply"
     cmds:
-      - task: check-rwp-config
       - |
-        BASE_DIR="output/workspaces/${RW_WORKSPACE}/slxs"
-        if [ ! -d "$BASE_DIR" ]; then
-          echo "Directory $BASE_DIR does not exist. Deletion aborted."
+        # Source Envs for Auth
+        source terraform/tf.secret
+
+
+        # Navigate to the Terraform directory
+        if [ -d "terraform" ]; then
+          cd terraform
+        else
+          echo "Terraform directory not found. Terraform apply aborted."
+          exit 1
+        fi
+        task format-and-init-terraform
+        echo "Starting Terraform Build of Terraform infrastructure..."
+        terraform apply -auto-approve || {
+          echo "Failed to clean up Terraform infrastructure."
+          exit 1
+        }
+        echo "Terraform infrastructure build completed."
+    silent: true
+
+  cleanup-terraform-infra:
+    desc: "Cleanup deployed Terraform infrastructure"
+    cmds:
+      - |
+        # Source Envs for Auth
+        source terraform/tf.secret
+
+        # Navigate to the Terraform directory
+        if [ -d "terraform" ]; then
+          cd terraform
+        else
+          echo "Terraform directory not found. Cleanup aborted."
           exit 1
         fi
 
-        for dir in "$BASE_DIR"/*; do
-          if [ -d "$dir" ]; then
-            SLX_NAME=$(basename "$dir")
-            URL="https://${RW_API_URL}/api/v3/workspaces/${RW_WORKSPACE}/branches/main/slxs/${SLX_NAME}"
-            echo "Deleting SLX: $SLX_NAME from $URL"
-            response_code=$(curl -X DELETE "$URL" \
-              -H "Authorization: Bearer $RW_PAT" \
-              -H "Content-Type: application/json" \
-              -w "%{http_code}" -o /dev/null -s)
-            
-            if [[ "$response_code" == "200" || "$response_code" == "204" ]]; then
-              echo "Successfully deleted SLX: $SLX_NAME from $URL"
-            elif [[ "$response_code" == "405" ]]; then
-              echo "Failed to delete SLX: $SLX_NAME from $URL. Method not allowed (405)."
-            else
-              echo "Failed to delete SLX: $SLX_NAME from $URL. Unexpected response code: $response_code"
-            fi
-          fi
-        done
+        echo "Starting cleanup of Terraform infrastructure..."
+        terraform destroy -auto-approve || {
+          echo "Failed to clean up Terraform infrastructure."
+          exit 1
+        }
+        echo "Terraform infrastructure cleanup completed."
     silent: true
 
+  check-and-cleanup-terraform:
+    desc: "Check and clean up deployed Terraform infrastructure if it exists"
+    cmds:
+      - |
+        # Capture the output of check-terraform-infra
+        infra_output=$(task check-terraform-infra | tee /dev/tty)
+
+        # Check if output contains indication of deployed infrastructure
+        if echo "$infra_output" | grep -q "Deployed infrastructure detected"; then
+          echo "Infrastructure detected; proceeding with cleanup."
+          task cleanup-terraform-infra
+        else
+          echo "No deployed infrastructure found; no cleanup required."
+        fi
+    silent: true
 
   clean-rwl-discovery:
     desc: "Check and clean up RunWhen Local discovery output"
     cmds:
       - |
-        sudo rm -rf output
-        rm -f workspaceInfo.yaml
-        rm -f kubeconfig
+        rm -rf output
+        rm workspaceInfo.yaml
     silent: true
